### ISSUE TITLE
No table generated by `interactive_group_setting`

### ISSUE THREAD

**Issue by calebweinreb** [dattalab/keypoint-moseq#52]
I get the following output when running `interactive_group_setting`:
<img width="1238" alt="Screenshot 2023-05-24 at 9 44 16 AM" src="https://github.com/dattalab/keypoint-moseq/assets/6147762/d6acd127-0bef-444c-b961-877fe773f820">

Is that intended? Or are there supposed to be rows for the various recordings? My index.yaml file seems to be fully populated:

```
files:
- filename: 21_11_8_one_mouse.top.irDLC_resnet50_moseq_exampleAug21shuffle1_500000
  group: default
  uuid: ae4f8e94-53e3-49a0-8cd6-8ae29ad63952
- filename: 21_12_10_def6a_1_1.top.irDLC_resnet50_moseq_exampleAug21shuffle1_500000
  group: default
  uuid: 217f6b8c-cfb9-4e3a-90fc-d2d7d6c1e8ec
- filename: 21_12_10_def6a_3.top.irDLC_resnet50_moseq_exampleAug21shuffle1_500000
  group: default
  uuid: 558adfe5-3351-4244-971c-5ad5345b2481
- filename: 21_12_10_def6b_3.top.irDLC_resnet50_moseq_exampleAug21shuffle1_500000
  group: default
  uuid: bd58f1ed-e3c3-4bfc-8f3c-3b75e7f523bf
- filename: 21_12_2_def6a_1.top.irDLC_resnet50_moseq_exampleAug21shuffle1_500000
  group: default
  uuid: 1d588560-104a-41c5-9c60-ce332380c8a2
- filename: 21_12_2_def6b_2.top.irDLC_resnet50_moseq_exampleAug21shuffle1_500000
  group: default
  uuid: cadc2edb-5ccd-490d-9f89-7783470c611e
- filename: 22_04_26_cage4_0.top.irDLC_resnet50_moseq_exampleAug21shuffle1_500000
  group: default
  uuid: 3853f96f-a62a-4af3-8a62-199de2a0688b
- filename: 22_04_26_cage4_0_2.top.irDLC_resnet50_moseq_exampleAug21shuffle1_500000
  group: default
  uuid: e7608a8e-d6e0-43ab-a855-d4070ecfaa06
- filename: 22_04_26_cage4_1_1.top.irDLC_resnet50_moseq_exampleAug21shuffle1_500000
  group: default
  uuid: e402beff-acb0-4e2d-9cd8-9835a80c5ee5
- filename: 22_27_04_cage4_mouse2_0.top.irDLC_resnet50_moseq_exampleAug21shuffle1_500000
  group: default
  uuid: 053f1e4e-15c4-4dc3-804d-972c22fa571a
```

and here's my `progress.yaml` file

```
base_dir: demo_project/
config_file: demo_project/config.yml
crowd_movie_dir: demo_project/2023_05_23-15_19_03/crowd_movies
grid_movie_dir: demo_project/2023_05_23-15_19_03/grid_movies
index_file: demo_project/index.yaml
model_checkpoint: demo_project/2023_05_23-15_19_03/checkpoint.p
model_dir: demo_project/2023_05_23-15_19_03/
model_name: 2023_05_23-15_19_03/
model_results: demo_project/2023_05_23-15_19_03/results.h5
plot_dir: demo_project/2023_05_23-15_19_03/plots
progress_filepath: demo_project/progress.yaml
syll_info_path: demo_project/syll_info.yaml
trajectory_plot_dir: demo_project/2023_05_23-15_19_03/trajectory_plots
```
